version: "3.1"

services:
  db:
    image: mysql:8.2
    container_name: break-bonanza-mysql-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
    - ./docker-data/db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  adminer:
    depends_on: 
    - db
    image: adminer
    restart: always
    ports:
      - 8080:8080
